name: test suite
on:
  push:
    branches-ignore:
        - "gh-readonly-queue/**"
  pull_request:
  merge_group:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master; avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.85"
      - run: cargo test --all-targets
      - run: cargo test --doc

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master; avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.85"
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master; avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.85"
          components: clippy
      - run: cargo clippy -- -D warnings

  allgreen:
    if: always()
    needs:
      - test
      - fmt
      - clippy
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
